export default {
    "en": {
        "nav.locale" : "Chinese/English",
        "nav.demoVideo" : "Demo Video",
        "nav.introdection" : "Introduction",
        "nav.tryItYourself" : "Try it yourself!",
        "intro.title" : "How it works",
        "intro.single" : "In single mode, input the product name, output the classification result and the accuracy.",
        "intro.batch" : "In batch mode, input the csv file having only one column ITEM_NAME, output the sunburst diagram (data visualization) and user can download the classified file.",
        "intro.csv" : " ",
        "file.mode" : "Batch Mode",
        "file.sunburst" : "Open Model",
        "file.downloadCSV" : "Download Example CSV",
        "file.uploadCSV" : "Upload CSV",
        "file.download" : "Download",
        "file.modeSelect1" : "Efficiency Priority",
        "file.modeSelect2" : "Precision Priority",
        "single.progress" : "Accuracy      ",
        "single.mode" : "Single Mode",
        "single.start" : "Get Started!",
        "single.input" : "Product Name",
    },
    "zh": {
        "nav.locale" : "中文/英文",
        "nav.demoVideo" : "演示视频",
        "nav.introdection" : "功能介绍",
        "nav.tryItYourself" : "应用模块",
        "intro.title" : "使用方法",
        "intro.single" : "单输入模式：输入商品名，点击提交按钮，系统返回类别以及可信度。",
        "intro.batch" : "批处理模式：上传csv文件，系统返回可视化结果，用户可以点击下载按钮下载预测文件。",
        "intro.csv" : "注：csv文件只有一列，且列名为ITEM_NAME；如果预测文件出现乱码，请将解码修改为gb18030。",
        "file.mode" : "批处理模式",
        "file.sunburst" : "可视化模型",
        "file.downloadCSV" : "下载测试文件",
        "file.uploadCSV" : "上传待分类文件",
        "file.download" : "预测结果下载",
        "file.modeSelect1" : "效率优先",
        "file.modeSelect2" : "精度优先",
        "single.progress" : "可信度      ",
        "single.mode" : "单输入模式",
        "single.start" : "提交",
        "single.input" : "输入产品名称",
    }
}
